In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]

In [3]:
np.array(lst)

array([1, 2, 3, 4, 5])

In [4]:
lst = [[1,2,3],[4,5,6],[7,8,9]]


In [5]:
np.array(lst)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.linspace(0,3)

array([0.        , 0.06122449, 0.12244898, 0.18367347, 0.24489796,
       0.30612245, 0.36734694, 0.42857143, 0.48979592, 0.55102041,
       0.6122449 , 0.67346939, 0.73469388, 0.79591837, 0.85714286,
       0.91836735, 0.97959184, 1.04081633, 1.10204082, 1.16326531,
       1.2244898 , 1.28571429, 1.34693878, 1.40816327, 1.46938776,
       1.53061224, 1.59183673, 1.65306122, 1.71428571, 1.7755102 ,
       1.83673469, 1.89795918, 1.95918367, 2.02040816, 2.08163265,
       2.14285714, 2.20408163, 2.26530612, 2.32653061, 2.3877551 ,
       2.44897959, 2.51020408, 2.57142857, 2.63265306, 2.69387755,
       2.75510204, 2.81632653, 2.87755102, 2.93877551, 3.        ])

In [9]:
arr = np.arange(25)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
array = np.random.randint(0,50,10) # random int number

In [13]:
array

array([26, 47, 40, 42, 47, 25, 32, 36, 31,  5])

In [33]:
newarray = np.arange(1,25)

In [34]:
newarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [35]:
slice_of_arr = newarray[0:10]

In [36]:
slice_of_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
slice_of_arr[:] = 99

In [38]:
slice_of_arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [39]:
newarray

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [40]:
newarray_copy = newarray.copy() # make a copy

In [42]:
newarray_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [43]:
newarray_copy[:] = 100

In [44]:
newarray_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [45]:
newarray

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])